// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNhU82sv-Z5_-CuGrQXh_GVBwgBOD7pY',
    appId: '1:413222616674:web:ac3bd47bccd0feaf355b3b',
    messagingSenderId: '413222616674',
    projectId: 'my-flutterfire-project434324',
    authDomain: 'my-flutterfire-project434324.firebaseapp.com',
    storageBucket: 'my-flutterfire-project434324.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOp01NgGUs495xecCJSDXHvBy0KsG6hI',
    appId: '1:413222616674:android:df6d64c631a57e3e355b3b',
    messagingSenderId: '413222616674',
    projectId: 'my-flutterfire-project434324',
    storageBucket: 'my-flutterfire-project434324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8lYgtHZgpfEeWA6dG-O-AZdbELipuYU',
    appId: '1:413222616674:ios:7ef67d00cde364c3355b3b',
    messagingSenderId: '413222616674',
    projectId: 'my-flutterfire-project434324',
    storageBucket: 'my-flutterfire-project434324.firebasestorage.app',
    iosBundleId: 'com.kenant42.flutterfirebasestudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8lYgtHZgpfEeWA6dG-O-AZdbELipuYU',
    appId: '1:413222616674:ios:7ef67d00cde364c3355b3b',
    messagingSenderId: '413222616674',
    projectId: 'my-flutterfire-project434324',
    storageBucket: 'my-flutterfire-project434324.firebasestorage.app',
    iosBundleId: 'com.kenant42.flutterfirebasestudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNhU82sv-Z5_-CuGrQXh_GVBwgBOD7pY',
    appId: '1:413222616674:web:4c3d138d6f38594d355b3b',
    messagingSenderId: '413222616674',
    projectId: 'my-flutterfire-project434324',
    authDomain: 'my-flutterfire-project434324.firebaseapp.com',
    storageBucket: 'my-flutterfire-project434324.firebasestorage.app',
  );
}
